### ISSUE TITLE
Challenge design

### ISSUE THREAD

**Issue by lbxa** [lbxa/o#34]
Yes, there are better naming choices you can make to make these concepts more straightforward for users to understand. Clear and intuitive naming is crucial for user engagement and ease of use. Let's revisit your current terms and explore how we can improve them both in your data model and in the user interface (UI).

### Categories

- **Current Names**: "Reps", "Time", "Weight", "Distance", "Social"
- **Issues**:
  - **"Reps"**: May be acceptable, but "Repetitions" is clearer.
  - **"Social"**: Vague; users may not understand what "Social" entails.

### Metrics

- **Current Names**: "Numerical", "Duration", "Change"
- **Issues**:
  - **"Numerical"**: Abstract; could be more specific.
  - **"Change"**: Ambiguous; could mean different things.

### Metric Options

- **Current Names**: "Min", "Max", "Target", "Shortest", "Longest"
- **Issues**:
  - **"Min"/"Max"**: Could be unclear whether it's about achieving at least a minimum or as much as possible.
  - **"Target"**: Generally understandable but could be more specific.

### Categories → **Activity Types**

**Rationale**: "Activity Type" is more descriptive and immediately tells the user that they are selecting the kind of activity the challenge involves.

- **Reps** → **Repetitions**
- **Time** → **Time-Based Activities**
- **Weight** → **Weightlifting**
- **Distance** → **Distance-Based Activities**
- **Social** → **Engagement Activities** or **Community Challenges**

**Explanation**:

- **"Repetitions"**: Clarifies that the challenge involves counting the number of times an activity is performed.
- **"Time-Based Activities"**: Specifies that the challenge is measured in time.
- **"Weightlifting"**: Clearly indicates that the challenge involves lifting weights.
- **"Distance-Based Activities"**: Clarifies that the challenge involves covering a certain distance.
- **"Engagement Activities"**: More specific than "Social"; implies activities that involve social interaction or community participation.

### Metrics → **Progress Measurement**

**Rationale**: "Progress Measurement" directly tells the user how their progress will be tracked.

- **Numerical** → **Count-Based**
- **Duration** → **Time-Based**
- **Change** → **Improvement Over Time**

**Explanation**:

- **"Count-Based"**: Indicates that progress is measured by counting (e.g., number of push-ups).
- **"Time-Based"**: Clearly shows that time is the measurement (e.g., time spent running).
- **"Improvement Over Time"**: Specifies that the focus is on progress or change from a baseline.

### Metric Options → **Goal Types**

**Rationale**: "Goal Types" is more user-friendly and directly relates to what users are setting for the challenge.

- **Min** → **Minimum Goal**
- **Max** → **Maximum Effort**
- **Target** → **Specific Target**
- **Shortest** → **Shortest Time**
- **Longest** → **Longest Duration**

**Explanation**:

- **"Minimum Goal"**: Clearly states that the objective is to achieve at least a certain amount.
- **"Maximum Effort"**: Encourages users to do as much as possible.
- **"Specific Target"**: Indicates aiming for a precise number or value.
- **"Shortest Time"**: Specifies that the goal is to complete something in the shortest possible time.
- **"Longest Duration"**: Aims for the longest time spent on an activity.

### Units

**Suggestion**: Use full names and consider adding abbreviations in parentheses for clarity.

- **kg** → **Kilograms (kg)**
- **lb** → **Pounds (lb)**
- **m** → **Meters (m)**
- **ft** → **Feet (ft)**
- **seconds** → **Seconds (s)**
- **minutes** → **Minutes (min)**
- **hours** → **Hours (h)**
- **mi** → **Miles (mi)**
- **km** → **Kilometers (km)**

**Explanation**:

- Using both full names and abbreviations ensures clarity, especially for international users who may be more familiar with one unit system over another.

## Revised Data Model

To reflect these changes in your data model, consider the following renamings:

```mermaid
erDiagram
    ACTIVITY_TYPE {
        number id PK
        string name
    }
    PROGRESS_MEASUREMENT {
        number id PK
        string name
    }
    GOAL_TYPE {
        number id PK
        number progress_measurement_id FK
        string name
    }
    UNIT {
        number id PK
        string name
        number activity_type_id FK
    }
    CHALLENGE_CONFIGURATION {
        number id PK
        number activity_type_id FK
        number goal_type_id FK
        number unit_id FK
        decimal target_value
    }
    CHALLENGE {
        number id PK
        string name
        string description
        number community_id FK
        number challenge_configuration_id FK
        datetime start_date
        datetime end_date
        datetime created_at
        datetime updated_at
    }
    CHALLENGE_ACTIVITY {
        number id PK
        number challenge_membership_id FK
        datetime activity_date
        number unit_id FK
        decimal value
    }
    
    ACTIVITY_TYPE ||--o{ UNIT : "has units"
    PROGRESS_MEASUREMENT ||--o{ GOAL_TYPE : "has goal types"
    ACTIVITY_TYPE ||--o{ CHALLENGE_CONFIGURATION : "used in"
    GOAL_TYPE ||--o{ CHALLENGE_CONFIGURATION : "used in"
    UNIT ||--o{ CHALLENGE_CONFIGURATION : "used in"
    CHALLENGE_CONFIGURATION ||--o{ CHALLENGE : "defines"
    CHALLENGE ||--|{ CHALLENGE_ACTIVITY : "records"
```

**Explanation**:

- **CATEGORY** → **ACTIVITY_TYPE**
- **METRIC** → **PROGRESS_MEASUREMENT**
- **METRIC_OPTION** → **GOAL_TYPE**
- **CHALLENGE_TYPE** → **CHALLENGE_CONFIGURATION**

These changes make the data model terms more aligned with user-friendly language, enhancing both developer understanding and user experience.

### Component Renaming

- **`ChallengeTypeSelector`** → **`ChallengeSetup`** or **`CreateChallenge`**

**Explanation**: A name like `ChallengeSetup` or `CreateChallenge` better conveys the purpose of the component.

### Labels and Instructions

**Current**:

- "Select a category"
- "Select a metric"
- "Select a target"

**Revised**:

1. **Select Activity Type**

   - **Label**: "What kind of activity is this challenge?"
   - **Options**: "Repetitions", "Time-Based Activities", "Weightlifting", "Distance-Based Activities", "Engagement Activities"

2. **Choose How to Measure Progress**

   - **Label**: "How will participants track their progress?"
   - **Options** depend on the selected activity type for better contextual relevance.

3. **Set a Goal**

   - **Label**: "What is the goal of this challenge?"
   - **Options**:
     - "Minimum Goal": Achieve at least a certain amount.
     - "Maximum Effort": Do as much as possible.
     - "Specific Target": Aim for a precise number.
     - "Shortest Time": Complete an activity in the shortest time.
     - "Longest Duration": Spend the longest time on an activity.

4. **Select Units (if applicable)**

   - **Label**: "Choose units for measurement"
   - **Options**: Display units relevant to the selected activity type.

5. **Enter Target Value (if applicable)**

   - **Label**: "Set the target value for the challenge"
   - **Placeholder**: "e.g., 100, 50.5"

**Example**:

- **Activity Type**: "Distance-Based Activities"
- **Progress Measurement**: "Time-Based"
- **Goal Type**: "Specific Target"
- **Units**: "Kilometers (km)"
- **Target Value**: "100"

### Simplifying the User Flow

- **Dynamic Options**: Only show relevant options based on previous selections to avoid overwhelming the user.
- **Tooltips and Descriptions**: Provide brief explanations or examples next to options to aid understanding.
- **Validation Messages**: Use clear and friendly language in error messages.

**Example of a User-Friendly Flow**:

1. **"What kind of challenge are you creating?"**

   - User selects **"Distance-Based Activities"**.

2. **"How will participants track their progress?"**

   - Show options like **"Distance Covered"**, **"Time Spent"**.

3. **"What is the goal of this challenge?"**

   - Options are adjusted based on the measurement method.

4. **"Choose units for measurement"**

   - Show only units relevant to distance, e.g., **"Kilometers (km)"**, **"Miles (mi)"**.

5. **"Set the target value for the challenge"**

   - Only if the goal type requires a target value.

## Enhancing Clarity Through Examples

Provide examples within the UI to help users understand the selections.

- **Activity Type Example**: "Distance-Based Activities (e.g., running, cycling)"
- **Goal Type Example**: "Specific Target (e.g., run 100 km in a month)"

## Additional Tips

- **Consistency**: Ensure that the terminology is consistent throughout the app to avoid confusion.
- **User Testing**: Conduct usability testing to see how real users interact with the new terms and adjust accordingly.
- **Internationalization**: If you have users from different regions, consider how terms translate and whether they remain clear.

## Updating the Code

Reflect these naming changes in your TypeScript code to maintain consistency between the frontend and backend.

### TypeScript Types

```typescript
type ActivityType = "Repetitions" | "Time-Based Activities" | "Weightlifting" | "Distance-Based Activities" | "Engagement Activities";

type ProgressMeasurement = "Count-Based" | "Time-Based" | "Improvement Over Time";

type GoalType = "Minimum Goal" | "Maximum Effort" | "Specific Target" | "Shortest Time" | "Longest Duration";

type Unit = "Kilograms (kg)" | "Pounds (lb)" | "Meters (m)" | "Feet (ft)" | "Seconds (s)" | "Minutes (min)" | "Hours (h)" | "Miles (mi)" | "Kilometers (km)";
```

### Component Updates

- **`PillGroupProps`**: Update properties to reflect new names.
- **`ChallengeSetupForm`**: Rename the form interface for clarity.

### Sample Code Snippet

```tsx
const activityTypes: ActivityType[] = [
  "Repetitions",
  "Time-Based Activities",
  "Weightlifting",
  "Distance-Based Activities",
  "Engagement Activities",
];

const progressMeasurements: { label: ProgressMeasurement; options: GoalType[] }[] = [
  {
    label: "Count-Based",
    options: ["Minimum Goal", "Maximum Effort", "Specific Target"],
  },
  {
    label: "Time-Based",
    options: ["Shortest Time", "Longest Duration"],
  },
  {
    label: "Improvement Over Time",
    options: ["Minimum Goal", "Maximum Effort", "Specific Target"],
  },
];
```

## Conclusion

By adopting more descriptive and user-friendly terms, you enhance both the usability of your app and the clarity of your codebase. Remember that the goal is to make it as easy as possible for users to create and participate in challenges without confusion.

---

**Next Steps:**

1. **Implement Renaming**: Update all instances of the old terms in your codebase and data model to the new terms.
2. **Update Documentation**: Ensure that all documentation reflects the new terminology.
3. **User Feedback**: After implementing the changes, gather user feedback to see if the new terms are clearer.
4. **Continuous Improvement**: Be open to further adjustments based on user interactions and feedback.

---

Feel free to reach out if you need assistance with any specific part of the implementation or have further questions!

**Comment by lbxa** [comment]
@JamieGom I've dropped our business domain into gpt-o1 and asked for feedback and I found it pretty good.

Thoughts on the recommendations? I think that golden retriever might feel more included now 🐕

**Comment by lbxa** [comment]
![Image](https://github.com/user-attachments/assets/e7a47dd4-64c6-4e0b-9b63-509b62836d3d)

This is a refreshed UI based on the above changes.

**Comment by JamieGom** [comment]
Nice, that was extremely useful ! Didn't know gpt could do that, we should offer it an internship. UI looks a lot more clear and user friendly :)

**Comment by lbxa** [comment]
![Image](https://github.com/user-attachments/assets/a8863117-71ef-4ea1-ae1e-ec4cd3f0dbc8)

Now we can handle `%` increase.

**Comment by lbxa** [comment]
@JamieGom any ideas on something better than `Count-based`.
