### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by lbxa** [lbxa/o#37]
Design a nice splash screen. ![Image](https://github.com/user-attachments/assets/05b28e7e-c579-4040-a6a3-482b9f9fab26)

--------

Use this link for context.

https://uxdesign.cc/building-the-perfect-splash-screen-46e080395f06

**Visual option one** 
￼

![Image](https://github.com/user-attachments/assets/f147df38-8682-4cf8-8998-2e77407b6694)

Note: watch the clip from the website to see animation 
 We could implement a:

Option one: 
- Trace oNex (like animation)
- Purple backdrop

Option two: 
- Trace oNex
- Purple backdrop 
- white circle emerges from background and engulfs oNex and then app opens // or circle just surrounds oNex // or circle goes above oNex 

Option three - simplicity 
- To make 1 second - maybe just have little o, the same purple, Nex is white but no animation 

-------- 

**Visualisation two** 

![Image](https://github.com/user-attachments/assets/bf110e5c-dbdd-4135-a1bd-78fc3f3d69c9)

￼
note: look at its animation on site 

We use a :
- circle : half purple / blue —> circle is centre of screen and bigger in size 
- Circle rotates 
- As circle rotates , oNex is written under the in in motion with its turn 

**Visualisation three** 
￼![Image](https://github.com/user-attachments/assets/399bc213-cd86-4ae0-881f-5b8233235378)

More complex animation 

- Similar background , pulsing white circles moving outside screen, purple background 
- oNex in centre

**Comment by lbxa** [comment]
@JamieGom I actually like no. 1 the most tbh. Our main indigo brand colour looks so good on its own 😍

I watched an episode of Keeping up with the Kardashians as this was a Kim quote:

> No one puts bumperstickers on a Ferrari

🤣

**Comment by lbxa** [comment]
![image](https://github.com/user-attachments/assets/774c125c-0b3c-4a13-b3b1-4c9145355c2b)

This is what we currently have. Should we just place a circle in the middle of this one?

**Comment by JamieGom** [comment]
> @JamieGom I actually like no. 1 the most tbh. Our main indigo brand colour looks so good on its own 😍
> 
> I watched an episode of Keeping up with the Kardashians as this was a Kim quote:
> 
> > No one puts bumperstickers on a Ferrari
> 
> 🤣

that's a gold comment haha

**Comment by JamieGom** [comment]
Do you mean that circle design or another? But yea I reckon make it simple with the circle -- are we gonna trace oNex or to too much??

**Comment by lbxa** [comment]
@JamieGom right now this is what we got

https://www.figma.com/design/UMLKmi9ZtwLKzTFWWURAzQ/App-Assets?node-id=0-1&node-type=canvas&t=8C4o2sYlEi21aiig-0
