### ISSUE TITLE
Empty list messaging

### ISSUE THREAD

**Issue by lbxa** [lbxa/o#38]
Right now empty list look really dead. Need to spice these up with either some better callouts or gifs.

![Image](https://github.com/user-attachments/assets/20608115-7c90-4a92-83d5-434e14166928)

![Image](https://github.com/user-attachments/assets/657e6f37-6586-49ba-9da3-6bbd7167869f)

**Comment by lbxa** [comment]
@JamieGom not making this as super high priority - but at the beginning most users will be seeing empty screens since we have no content yet!

**Comment by JamieGom** [comment]
I think as a coming soon feature, maybe we do our own oNex community? Can create public challenges for users to join? 

Later stage, like unofficial run club, once we get numbers, could even plan big meet ups, like a group training session.

I'll think of other things in the meantime

**Comment by JamieGom** [comment]
Another thought - Can set monthly individual challenges. For example the "December push up/ plank hold challenge." Every day a user puts in their daily push ups or plank hold time and they can see their progress at the end. Just an easy challenge each month to hold them accountable for personal progress. 

----
Later stage add stats to the challenge, e.g., You were in the top x% of users. Badges. Then users can share their stats ....

**Comment by lbxa** [comment]
I like the idea. I'll create a new ticket around oNex official challenges.
